# Generated by Django 4.2.2 on 2023-08-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='extra_test_mark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='final_test_mark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='first_tcp_mark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='mundial_test_mark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='second_tcp_mark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.CreateModel(
            name='Subjectmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_tcp_mark', models.IntegerField(blank=True)),
                ('second_tcp_mark', models.IntegerField(blank=True)),
                ('third_tcp_mark', models.IntegerField(blank=True)),
                ('final_test_mark', models.IntegerField(blank=True)),
                ('extra_test_mark', models.IntegerField(blank=True)),
                ('mundial_test_mark', models.IntegerField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolms.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolms.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(through='schoolms.Subjectmarks', to='schoolms.student'),
        ),
    ]
