# Generated by Django 4.2.2 on 2023-07-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='stored',
            field=models.BooleanField(default=True),
        ),
    ]
